### ISSUE TITLE
[US36] Definir as questões de criação de comunidade e criar no banco

### ISSUE THREAD

**Issue by guilherme1guy** [fga-eps-mds/2021.1-Cartografia-social-api-comunidades#9]
# Descrição:
Solicitar quais são as quetões que são necessarias para cirar uma comunidade e cadastra-las no banco de dados.

# Tarefas:
- [x] Solicitar a cliente quais são as questões
- [ ] Cadastrar no banco de produção
- [x] Cadastras no banco de homologação
- [x] Criar arquivo de seed para desenvolvimento

# Critério de aceitação:
- [x] Questões são criadas no banco
- [x] É possível resgatar as questões chamando a API

**Comment by arthurarp** [comment]
Link para as questões -> https://docs.google.com/document/d/1XLO08VnuH1yzZcEu1jyOUwMkaXcSjzq2/edit?usp=sharing&ouid=101483190110086583311&rtpof=true&sd=true
